import type { Metadata } from 'next';
import { getSession } from 'next-auth/react';
import { Geist, Geist_Mono } from 'next/font/google';
import AuthProvider from '@/components/Providers/Auth';

import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'HackerMeet',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getSession();

	return (
		<AuthProvider session={session}>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen bg-gradient-to-b from-lime-500 to-blue-300 via-lime-400`}>
					{children}
				</body>
			</html>
		</AuthProvider>
	);
}
